name: "Bug"
description: "Report a defect with steps to reproduce"
title: "bug: <concise title>"
labels: ["type: bug", "status: triage"]
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS/Browser/Version
  - type: checkboxes
    id: safety
    attributes:
      label: Safety
      options:
        - label: Reproducible
        - label: Has logs/trace attached
        - label: Has failing test (if applicable)
