name: Auto formatting

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettify code
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --write .
          commit_message: "chore: Prettified code!"
