name: Update PROJECT_INFO (PR)

on:
  push:
    branches: [ master ]     # fires on direct pushes and PR merges to master
  workflow_dispatch:         # optional: let you run it manually

permissions:
  contents: write
  pull-requests: write

jobs:
  snapshot-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master (attach to branch, not SHA)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Install tree
        run: |
          sudo apt-get update
          sudo apt-get install -y tree

      - name: Generate tree
        env:
          SOURCE_DIR: src
        run: |
          mkdir -p PROJECT_INFO
          tree -a -I ".git|target|node_modules|PROJECT_INFO|.github" "$SOURCE_DIR" > PROJECT_INFO/source-tree.txt

      - name: Create or update PR
        uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/update-project-info               # fixed branch the bot reuses
          title: "chore: update PROJECT_INFO tree snapshot"
          commit-message: "chore: update PROJECT_INFO tree snapshot"
          body: "Automated update of PROJECT_INFO/source-tree.txt"
          add-paths: |
            PROJECT_INFO/**
          # optional:
          # labels: automation, housekeeping
          # draft: true
