name: Lint PR title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: read
  statuses: write   # recommended so the action can set a status

jobs:
  semantic-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity: can the token read this PR?
        uses: actions/github-script@v7
        with:
          script: |
            core.info(`event=${context.eventName}`)
            core.info(`pr_number=${context.payload.pull_request?.number}`)
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
            core.info(`PR title = ${pr.data.title}`)

      - name: Lint PR title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          subjectPattern: '^[^\s].+'
