name: Semantic PR

on:
   pull_request:
      types: [opened, edited, synchronize]

jobs:
   main:
      name: Validate PR title
      runs-on: ubuntu-latest
      permissions:
         pull-requests: read
         statuses: write
      steps:
         - uses: amannn/action-semantic-pull-request@v6
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
